    var Hexa=["0","1","2","3","4","5","6","7","8","9","A","B","C","D","E","F"];                                                                                                                              // On écrit le code hex
    var colonne = document.createElement('tr');                                                                                                                                                             // Je crée un élement tr pour le tableau 
    document.getElementById('Tableau').appendChild(colonne);                                                                                                                                                // J'ajoute l'élément tr à l'élément tableau 
    for(var x=0;x<=288;x++){                                                                                                                                                                                // Je vais crée un tableau 17 * 17 
        var cellule = document.createElement('td');                                                                                                                                                         // à chaque fois je crée une cellule
        cellule.className="Cellule";                                                                                                                                                                        // sa classe se nommera Cellule ( pour le css )
        cellule.id="Cellule_"+x;                                                                                                                                                                            // son id serra Cellule_x soit x la position du tableau
        colonne.appendChild(cellule);                                                                                                                                                                       // j'ajoute ma cellule à tr
        if(!(x>0&&x<=16)&&!(x%17==0&&x!=0)){cellule.appendChild(document.createTextNode(unescape(String.fromCharCode(x-18-parseInt(document.getElementById("Cellule_"+Math.trunc(x/17)).innerHTML,16)))));} // Si je suis dans l'espace réservé pour le code ascii alors j'ajoute une cellule avec un contenant dans tr. Ce contenant est le code ascii. Je récupère tout d'abord le code décimal de la table ascii puis je l'insère dans les fonctions unsecape et fromcharcode qui permette d'écrire le code ascii. Je le récupère le code décimal grâce à x-17( - 17 car je suis supprime la première ligne du tableau ) et [-parseInt(document.getElementById("Cellule_"+Math.trunc(x/17)).innerHTML,16)] qui sert à récupérer le code décimal de la cellule la plus à gauche de la ligne pour le soustraire. On le soustrait pour éviter le décalage de +1 à chaque ligne.  
        if(x>0&&x<=16){cellule.appendChild(document.createTextNode(Hexa[x-1]));}                                                                                                                            // Permet d'insérer le code hex dans la ligne 0
        if(x%17==0&&x!=0){cellule.appendChild(document.createTextNode(Hexa[(x-17)/17]));}                                                                                                                   // Permet d'insérer le code hex dans la colonne 0 
        if((x+1)%17==0){                                                                                                                                                                                    // Je regarde si j'arrive à la dernière case de ma ligne. Si c'est le cas j'insère une nouvelle ligne
            colonne = document.createElement('tr');
            document.getElementById('Tableau').appendChild(colonne);
        }
    }